package com.quantumos.quarkavatar

import androidx.annotation.DrawableRes
import androidx.compose.ui.graphics.Color
import com.quantumos.appshell.Phosphor
import com.quantumos.core.QuarkReflexPosture
import com.quantumos.core.SoundCue

/*
 * QUARK's expression states, exactly as `art/quark-avatar/reference/QUARK_Turnaround1.png` panel 04
 * defines them -- including the voice line each one is supposed to carry, because the plate and the
 * copy have to agree.
 *
 * These are STATES, not frames of an animation. The house style is explicit that QUARK is "static
 * at rest (zero idle redraw)" and that motion is "stepped, not interpolated", so switching state
 * swaps the plate outright: no crossfade, no tween. That is not a shortcut -- a hard cut IS the
 * house transition.
 *
 * IDLE is the delivered reference plate. SCAN / HAPPY / WARN were produced from it locally by
 * `comfy/flux2_state_plates.py` (Flux 2 Klein 4B, edit at denoise 0.45), then keyed through
 * `comfy/chroma_key.py` on a SHARED crop box so the four register and the avatar does not jump when
 * the state changes.
 *
 * There are TWO plate sets, and every state exists in both: the full BODY figure (the default
 * presentation since Phase 18) and the closer BUST. They were generated by the same script from the
 * two reference plates, each set keyed on its own shared crop box.
 */
enum class QuarkState(
    val label: String,
    @DrawableRes val plate: Int,
    @DrawableRes val bodyPlate: Int,
    val line: String,
    /**
     * Overrides the housing's phosphor for this state, or null to use the live hue.
     *
     * WARN is the only state that sets it. The plate already carries red on the ear modules and
     * neck circuitry -- but on device that read as merely LEGIBLE rather than loud, and an
     * access-denied state has to be unmistakable at a glance. Driving the whole projection housing
     * red is what fixes that: the light column and the CRT glow both go `--warn`, so
     * the alert is carried by the surface the Operator is already looking at rather than by detail
     * inside the art. It also keeps the rule where CLAUDE.md puts it -- `--warn` red is for alerts
     * and access-denied, never decoration -- instead of baking it into a texture.
     */
    val housingAccent: Color? = null,
    /**
     * QUARK's wordless chirp for this state, or null for a state that makes no sound.
     *
     * Kept HERE rather than in a when-block at the call site, for the same reason `line` and
     * `housingAccent` are: the plate, the voice line, the housing colour and the sound are four
     * expressions of one state, and splitting them across files is how they drift apart.
     *
     * These are the non-verbal chirps from the house style's sound palette -- wordless, and distinct
     * from QUARK's spoken voice. IDLE is silent on purpose: it is rest, and the house style is
     * explicit that motion and sound are reactive rather than ambient.
     */
    val cue: String? = null,
) {
    IDLE(
        "IDLE", R.drawable.quark_state_idle, R.drawable.quark_body_idle,
        "Quiet. Ready. Observant.",
    ),
    SCAN(
        "SCAN", R.drawable.quark_state_scan, R.drawable.quark_body_scan,
        "Focused. Analyzing. One moment.",
        cue = SoundCue.CHIRP_SCAN,
    ),
    HAPPY(
        "HAPPY", R.drawable.quark_state_happy, R.drawable.quark_body_happy,
        "Warmth. Approval.",
        cue = SoundCue.CHIRP_HAPPY,
    ),
    WARN(
        "WARN", R.drawable.quark_state_warn, R.drawable.quark_body_warn,
        "Clipped. Grave. No wit. No softening.",
        housingAccent = Phosphor.Warn,
        // WARN is an access-denied state and the house style says it has to be audible. This chirp
        // shares the denial language rather than being a second, softer alarm.
        cue = SoundCue.CHIRP_WARN,
    );

    /** The plate for this state in the active presentation. */
    @DrawableRes
    fun plateFor(mode: RenderMode): Int =
        if (mode == RenderMode.PLATE_BODY) bodyPlate else plate

    /** The engine posture this presentation state corresponds to. */
    val posture: QuarkReflexPosture
        get() = when (this) {
            IDLE -> QuarkReflexPosture.IDLE
            SCAN -> QuarkReflexPosture.SCAN
            HAPPY -> QuarkReflexPosture.HAPPY
            WARN -> QuarkReflexPosture.WARN
        }

    companion object {
        /**
         * The presentation state for an engine posture.
         *
         * The two enums are deliberately kept separate rather than the avatar using
         * `QuarkReflexPosture` directly: that one lives in `:core` and is Android-free, and this one
         * carries drawables, a Compose Color and a sound token. Mapping between them in one place is
         * the cost of that separation, and `when` with no else keeps the compiler responsible for
         * catching a fifth posture if one is ever added.
         */
        fun of(posture: QuarkReflexPosture): QuarkState = when (posture) {
            QuarkReflexPosture.IDLE -> IDLE
            QuarkReflexPosture.SCAN -> SCAN
            QuarkReflexPosture.HAPPY -> HAPPY
            QuarkReflexPosture.WARN -> WARN
        }
    }
}
